### ISSUE TITLE
sample[] no match found, skipping

### ISSUE THREAD

**Issue by andybru** [mrbombmusic/sonic-pi-drum-rnn-gui#1]
Hello and thank you for your very interesting code.

I managed to find the missing 'musicvae.js' under
"https://raw.githubusercontent.com/googlecreativelab/melody-mixer/master/third_party/musicvae/musicvae.js"

and so connected your visual Drum Pattern Interface to Sonic PI.

So the HTML sends KITS and Notes to Sonic PI.

But possibly with sonic pi 3.3.2 something changed
because there is no .index method on your dr-variable
in line 110
in your 'Sonic-Pi-receiver.rb' by default.

I thought like in some historic cases that adding .to_a
would be sufficient in line 100 in your code
but it does not seem so because now it does not
sound any thing because of the mentioned
'no match found' error.

Possibly you could revise/refresh your code a little bit.

Or give me little tweak advise.

Many thanks and a good day.

**Comment by andybru** [comment]
So I improved my ruby know how and fixed the issue myself.

Instead of .index(..) in line 106, 118, 119 i used .key(..)

which is working perfectly.

Thanks for listening.

**Comment by mrbombmusic** [comment]
Hi @andybru 
Glad to know you figured it out. I actually haven't tried this project with any of the 3.3 versions of Sonic Pi yet, so I appreciate you bringing this to my attention as it will probably save me a lot of aggravation in the future.
I do know that any Ruby code that is not directly a part of the Sonic Pi language is always susceptible to no longer being supported when there is an update, so my guess would be that was why this happened. 
Once I get around to updating to 3.3, I'll try to update the code here.
